### ISSUE TITLE
Retry FCM token update in case of failure

### ISSUE THREAD

**Issue by fmrsabino** [gnosis/safe-browser-extension#45]
While onboarding with the Chrome Extension the user shouldn't be able to proceed (scanning QR code) if the token registration was not successful with the backend.

This leads to safe creations which won't be acknowledged by the extension.

**Comment by rmeissner** [comment]
I disagree with this. The whole idea behind our current setup is that this is not required. This is currently solved by the possibility to resend the push from the app and in the future will be improved via the services.

**Comment by rmeissner** [comment]
But the chrome extension should automatically retry to sync the token if this was never successful before or if the token has changed

**Comment by fmrsabino** [comment]
The issue is that if for some reason the extension doesn't register its token correctly then the safe creation flow is basically stuck forever (with the current state of the extension).

We can make it a non blockable process I agree but it's still an issue with the current setup.

**Comment by rmeissner** [comment]
Exactly because of this case it is possible to resend the push from within the app.

**Comment by fmrsabino** [comment]
If app means Android app then I don't see how they are related. This is about registering the Chrome Extension FCM token.

https://github.com/gnosis/safe-browser-extension/blob/84b0f0cc2a7e791d1fc84d3dcb21a266f02f4223/app/routes/extension/DownloadApps/components/PairingProcess/containers/PairingProcess.js#L34-L47

There's no action to retry (or to have an active retry in the background as far as I can see) while you don't have any safes.

**Comment by rmeissner** [comment]
I do agree that this should be retried (automatically or manual for now). But I would not block the pairing progress for that. While the app is registering with the service it should be possible to already scan the qr code and submit the tx.

**Comment by fmrsabino** [comment]
Yeah updated the ticket to remove the "blocking" part.
